module.exports = Object.freeze({
	ROLE_MANAGER: 'ROLE_MANAGER',
	ROLE_BIKER: 'ROLE_BIKER',
	SHIPMENT_STATUS_WAITING: 'WAITING',
	SHIPMENT_STATUS_ASSIGNED: 'ASSIGNED',
	SHIPMENT_STATUS_PICKED_UP: 'PICKED_UP',
	SHIPMENT_STATUS_DELIVERED: 'DELIVERED'
});

